name: sit
on:
  push:
    branches:
      - sit
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 安装node
        uses: actions/setup-node@v1
        with:
          node-version: "20.0.0"
      - name: 安装依赖
        run: npm install
      - name: 打包
        run: npm run build
      - name: 部署
        uses: appleboy/scp-action@master
        with:
          source: "abstract-umi/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/sit/"
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          strip_components: 1
